-- MySQL Script generated by MySQL Workbench
-- Thu May 25 14:12:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forum_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forum_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forum_db` DEFAULT CHARACTER SET utf8 ;
USE `forum_db` ;

-- -----------------------------------------------------
-- Table `forum_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `register_token` VARCHAR(20) NOT NULL,
  `admin` TINYINT NOT NULL,
  `banned` TINYINT NOT NULL,
  `confirmed` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Unique_user` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Unique_category` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum_db`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum_db`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `image_link` VARCHAR(45) NULL,
  `closed` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_posts_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `forum_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forum_db`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forum_db`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `comment_id` INT NULL,
  `text` VARCHAR(2000) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `image_link` VARCHAR(45) NULL,
  `banned` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_posts1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_comments_comments1_idx` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `forum_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `forum_db`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `forum_db`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
